components:
  schemas:
    DefaultModelsResponseSchema:
      description: 'Schema to validate the /default-models GET response data '
      example:
      - accuracy: 0.92
        creationTime: 01-01-2025T06:21:00
        description: Classifies between spanish or not spanish.
        name: spanish_else
        nationalities:
        - spanish
        - else
        scores:
        - 0.89
        - 0.95
      items:
        $ref: '#/components/schemas/N2EModel'
      title: DefaultModelsResponseSchema
      type: array
    InferenceResponseSchema:
      additionalProperties:
        maxItems: 2
        minItems: 2
        prefixItems:
        - type: string
        - type: number
        type: array
      description: 'Schema to validate the /classify POST response data '
      example:
        Cixin Liu:
        - chinese
        - 0.91
        Jules Verne:
        - french
        - 0.75
        werner heisenberg:
        - german
        - 0.87
      title: InferenceResponseSchema
      type: object
    InferenceSchema:
      description: 'Schema to validate name classification request data '
      example:
        getDistribution: false
        modelName: chinese_german_french
        names:
        - Cixin Liu
        - werner heisenberg
        - Jules Verne
      properties:
        getDistribution:
          title: Getdistribution
          type: boolean
        modelName:
          title: Modelname
          type: string
        names:
          items:
            type: string
          title: Names
          type: array
      required:
      - modelName
      - names
      - getDistribution
      title: InferenceSchema
      type: object
    ModelsResponseSchema:
      description: 'Schema to validate the /models GET response data '
      example:
        customModels:
        - accuracy: 0.87
          creationTime: 01-01-2025T07:21:00
          description: Classifies between 3 ethnicities.
          name: chinese_german_french
          nationalities:
          - chinese
          - german
          - french
          scores:
          - 0.97
          - 0.85
          - 0.81
        defaultModels:
        - accuracy: 0.92
          creationTime: 01-01-2025T06:21:00
          description: Classifies between spanish or not spanish.
          name: spanish_else
          nationalities:
          - spanish
          - else
          scores:
          - 0.89
          - 0.95
      properties:
        customModels:
          items:
            $ref: '#/components/schemas/N2EModel'
          title: Custommodels
          type: array
        defaultModels:
          items:
            $ref: '#/components/schemas/N2EModel'
          title: Defaultmodels
          type: array
      required:
      - customModels
      - defaultModels
      title: ModelsResponseSchema
      type: object
    N2EModel:
      description: 'Schema to validate N2E Model data '
      example:
        accuracy: 0.87
        creationTime: 01-01-2025T07:21:00
        description: Classifies between 3 ethnicities.
        name: chinese_german_french
        nationalities:
        - chinese
        - german
        - french
        scores:
        - 0.97
        - 0.85
        - 0.81
      properties:
        accuracy:
          anyOf:
          - type: number
          - type: 'null'
          title: Accuracy
        creationTime:
          title: Creationtime
          type: string
        description:
          anyOf:
          - type: string
          - type: 'null'
          default: null
          title: Description
        name:
          title: Name
          type: string
        nationalities:
          items:
            type: string
          title: Nationalities
          type: array
        scores:
          anyOf:
          - items:
              type: number
            type: array
          - type: 'null'
          title: Scores
      required:
      - name
      - nationalities
      - accuracy
      - scores
      - creationTime
      title: N2EModel
      type: object
    NationalitiesSchema:
      description: 'Schema of the /nationalities response '
      example:
        nationalities:
          british: 6134933
          indian: 90347
          norwegian: 23920
        nationalitiyGroups:
          african: 104673
          angloAmerican: 112722
          eastAsian: 631015
      properties:
        nationalities:
          additionalProperties:
            type: integer
          title: Nationalities
          type: object
        nationalityGroups:
          additionalProperties:
            type: integer
          title: Nationalitygroups
          type: object
      required:
      - nationalities
      - nationalityGroups
      title: NationalitiesSchema
      type: object
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      description: For authorizing your requests, use the 'Authorization' header in
        the format of 'Bearer {token}'. To get your API token visit https://www.name-to-ethnicity.com
        and create an account.
      scheme: bearer
      type: http
info:
  contact:
    email: theodorpeifer@gmail.com
  description: This is the official REST API documentation for www.name-to-ethnicity.com.
    Using our public API you can classify names into their most likely ethnicity and
    retrieve a list of all your models.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.name-to-ethnicity.com/terms-of-service
  title: Name-to-ethnicity API
  version: 1.0.0
openapi: 3.0.3
paths:
  /classify:
    post:
      description: Classify names.
      operationId: classification_route
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InferenceSchema'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InferenceResponseSchema'
          description: Successful classification
        '401':
          description: Authentication failed
        '404':
          description: Model not found
        '422':
          description: Too many names
        '500':
          description: Internal server error
      security:
      - BearerAuth: []
      summary: Classify names.
      tags:
      - Classification
  /default-models:
    get:
      description: Get all default models.
      operationId: get_default_models_route
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultModelsResponseSchema'
          description: Successfully retrieved models.
        '500':
          description: Internal server error
      security:
      - BearerAuth: []
      summary: Get all default models.
      tags:
      - Models
  /models:
    get:
      description: Get all models.
      operationId: get_models_route
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModelsResponseSchema'
          description: Successfully retrieved models.
        '401':
          description: Authentication failed
        '500':
          description: Internal server error
      security:
      - BearerAuth: []
      summary: Get all models.
      tags:
      - Models
  /nationalities:
    get:
      description: Returns a list of all available nationalities (49) and nat. groups
        (8) along with the amount of samples we have of them in our dataset.
      operationId: get_nationalities_route
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NationalitiesSchema'
          description: Successfully retrieved nationalities
        '500':
          description: Internal server error
      security:
      - BearerAuth: []
      summary: Returns a list of all available nationalities (49) and nat. groups
        (8) along with the amount of samples we have of them in our dataset.
      tags:
      - Utilities
security:
- BearerAuth: []
servers:
- description: Production server
  url: https://api.name-to-ethnicity.com/
- description: Local server
  url: http://localhost:8080
tags:
- description: API endpoints for name classification.
  name: Classification
- description: API endpoints model management.
  name: Models
- description: Miscellaneous API endpoints.
  name: Utilities
