name: Test and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd123
      POSTGRES_PORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_HOST: localhost
      FLASK_ENV: test
      FLASK_APP: src/app.py
      JWT_SECRET: supersecret
      JWT_EXPIRATION_DAYS: 30

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest

  docker-push:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: name-ethnicity-classifier
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create image from repository
        run: docker build -t ghcr.io/name-ethnicity-classifier/n2e-backend .

      - name: Push image to GitHub Container Registry
        run: docker push ghcr.io/name-ethnicity-classifier/n2e-backend
