name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd123
      POSTGRES_PORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_HOST: localhost
      FLASK_ENV: test
      FLASK_APP: src/app.py
      JWT_SECRET: supersecret
      JWT_EXPIRATION_DAYS: 30
      MINIO_USER: minio-user
      MINIO_PASSWORD: minio-password
      MINIO_HOST: http://127.0.0.1
      MINIO_PORT: 9000
      MINIO_UI_PORT: 9001
      MINIO_ACCESS_KEY_ID: minio-key-id
      MINIO_SECRET_ACCESS_KEY: minio-secret-key
      MODEL_S3_BUCKET: models
      BASE_DATA_S3_BUCKET: base-data
      BASE_MODEL: conv_lstm_v1
      MAX_NAMES: 10
      BATCH_SIZE: 30
      MAX_MODELS: 3
      DAILY_QUOTA: 100000
      RESEND_API_KEY: resend-secret
      USER_VERIFICATION_ACTIVE: False

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest